{
 "title": "DevOps Final Project Observability",
 "tags": [
  "devops",
  "fastapi",
  "observability"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Backend Up/Down Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"fastapi-backend\"}",
     "legendFormat": "backend"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(app_requests_total{job=\"fastapi-backend\"}[1m]))",
     "legendFormat": "requests/sec"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(app_errors_total{job=\"fastapi-backend\"}[1m]))",
     "legendFormat": "errors/sec"
    }
   ]
  },
  {
   "title": "p95 Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_request_duration_seconds_bucket{job=\"fastapi-backend\"}[5m])) by (le))",
     "legendFormat": "p95 latency"
    }
   ]
  },
  {
   "title": "Deployments Created",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_deployments_created_total{job=\"fastapi-backend\"}",
     "legendFormat": "created"
    }
   ]
  },
  {
   "title": "Recent Backend Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "{job=\"backend-json-logs\", service=\"backend\"} | json"
    }
   ]
  }
 ]
}